plugins {
    id 'com.android.application' version '9.4.1' apply false
    id 'com.android.legacy-kapt' version '9.4.1' apply false
    id 'com.google.dagger.hilt.android' version '2.60.1' apply false
    id 'androidx.navigation.safeargs.kotlin' version '2.10.2' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
